logging:
  level:
    root: INFO
  file:
    name: ./log/wendys-friends.log

spring:
  application:
    name: wendys-friends
  datasource:
    url: "jdbc:h2:./wendydb;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
server:
  port: 8080